### ISSUE TITLE
想请教一下dylib是怎么编译出来的呢

### ISSUE THREAD

**Issue by Nappp** [lichao890427/personal_script#2]
[Ret70/PTFakeTouch](https://github.com/Ret70/PTFakeTouch.git)已经迭代好多版，仓库里这个[Frida_script/PTFakeTouch.dylib](https://github.com/lich4/personal_script/blob/master/Frida_script/PTFakeTouch.dylib)可能不支持iOS14了。本人非iOS开发者，网上找了一圈都没有有效的方法产出dylib。有没有较为完整的指南呢，谢谢

**Comment by lich4** [comment]
源工程需要Mac下Xcode编译。支持14: https://github.com/tuxi/PTFakeTouch/tree/7dbaa2a32b4b8567c1eb27280e6cb1bcab45c279
